default:
  image: continuumio/miniconda3
  before_script:
    - apt-get update
    - apt-get install build-essential -y
    - apt-get install curl -y

pages:
  stage: deploy
  script:
    - make environment
    - make docs
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: "$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH"
