name: Deploy site
on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: "3.11"

      - name: Create conda environment
        run: make conda-create

      - name: Install conda dependenices
        run: make from-conda-lock

      - name: Install pip dependenices
        run: make install

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: make deploy
